# We use Dependabot to keep our dependencies up to date.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 3
    labels:
      - 'scope:dependencies'
    milestone: 4
  - package-ecosystem: 'github-actions'
    directory: '.github/actions/setup-install'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 3
    labels:
      - 'scope:dependencies'
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 3
    labels:
      - 'scope:dependencies'
    milestone: 4
  - package-ecosystem: 'docker'
    directory: '.devcontainer/Dockerfile'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 3
    labels:
      - 'scope:dependencies'
    milestone: 4
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 3
    labels:
      - 'scope:dependencies'
    milestone: 4
